export const mockGuests = [
    {
        id: 1,
        name: 'Sarah Johnson',
        title: 'Tech Entrepreneur & AI Expert',
        bio: 'Former VP at Google, now building AI startups. Passionate about democratizing technology and mentoring founders.',
        avatar: 'https://ui-avatars.com/api/?name=Sarah+Johnson&background=6366f1&color=fff',
        expertise: ['Artificial Intelligence', 'Startups', 'Leadership', 'Product Management'],
        rating: 4.9,
        reviewCount: 127,
        episodeCount: 45,
        price: 500,
        availability: 'Available',
        location: 'San Francisco, CA',
        languages: ['English', 'Spanish'],
    },
    {
        id: 2,
        name: 'Michael Chen',
        title: 'Bestselling Author & Productivity Coach',
        bio: 'Author of "The 5AM Revolution". Helping people unlock their potential through proven productivity systems.',
        avatar: 'https://ui-avatars.com/api/?name=Michael+Chen&background=8b5cf6&color=fff',
        expertise: ['Productivity', 'Personal Development', 'Writing', 'Habits'],
        rating: 4.8,
        reviewCount: 203,
        episodeCount: 78,
        price: 350,
        availability: 'Available',
        location: 'New York, NY',
        languages: ['English', 'Mandarin'],
    },
    {
        id: 3,
        name: 'Dr. Emily Rodriguez',
        title: 'Clinical Psychologist & Mental Health Advocate',
        bio: 'Specializing in workplace mental health and burnout prevention. Regular contributor to Psychology Today.',
        avatar: 'https://ui-avatars.com/api/?name=Emily+Rodriguez&background=ec4899&color=fff',
        expertise: ['Mental Health', 'Psychology', 'Wellness', 'Mindfulness'],
        rating: 5.0,
        reviewCount: 156,
        episodeCount: 62,
        price: 400,
        availability: 'Limited',
        location: 'Austin, TX',
        languages: ['English'],
    },
    {
        id: 4,
        name: 'James Patterson',
        title: 'Serial Entrepreneur & Investor',
        bio: 'Founded 3 successful startups (2 exits). Now angel investing and advising early-stage companies.',
        avatar: 'https://ui-avatars.com/api/?name=James+Patterson&background=10b981&color=fff',
        expertise: ['Entrepreneurship', 'Venture Capital', 'SaaS', 'Growth'],
        rating: 4.7,
        reviewCount: 89,
        episodeCount: 34,
        price: 600,
        availability: 'Available',
        location: 'Boston, MA',
        languages: ['English'],
    },
    {
        id: 5,
        name: 'Priya Sharma',
        title: 'Sustainability Expert & Climate Activist',
        bio: 'Leading the charge for corporate sustainability. TEDx speaker and UN Climate Summit participant.',
        avatar: 'https://ui-avatars.com/api/?name=Priya+Sharma&background=f59e0b&color=fff',
        expertise: ['Sustainability', 'Climate Change', 'ESG', 'Corporate Responsibility'],
        rating: 4.9,
        reviewCount: 142,
        episodeCount: 51,
        price: 450,
        availability: 'Available',
        location: 'Seattle, WA',
        languages: ['English', 'Hindi'],
    },
];

export const mockHosts = [
    {
        id: 1,
        name: 'Alex Rivera',
        podcastName: 'The Innovation Hour',
        description: 'Weekly conversations with innovators, entrepreneurs, and thought leaders shaping the future.',
        avatar: 'https://ui-avatars.com/api/?name=Alex+Rivera&background=6366f1&color=fff',
        category: 'Technology & Business',
        rating: 4.8,
        reviewCount: 98,
        episodeCount: 156,
        subscribers: 125000,
        platforms: ['Spotify', 'Apple Podcasts', 'YouTube'],
        recordingFormat: 'Video & Audio',
        averageLength: '45-60 min',
    },
    {
        id: 2,
        name: 'Lisa Thompson',
        podcastName: 'Mindful Living',
        description: 'Exploring wellness, mental health, and personal growth with experts and practitioners.',
        avatar: 'https://ui-avatars.com/api/?name=Lisa+Thompson&background=8b5cf6&color=fff',
        category: 'Health & Wellness',
        rating: 4.9,
        reviewCount: 134,
        episodeCount: 203,
        subscribers: 89000,
        platforms: ['Spotify', 'Apple Podcasts'],
        recordingFormat: 'Audio Only',
        averageLength: '30-45 min',
    },
    {
        id: 3,
        name: 'David Kim',
        podcastName: 'Startup Stories',
        description: 'Real stories from founders who built successful companies from scratch.',
        avatar: 'https://ui-avatars.com/api/?name=David+Kim&background=ec4899&color=fff',
        category: 'Entrepreneurship',
        rating: 4.7,
        reviewCount: 76,
        episodeCount: 89,
        subscribers: 67000,
        platforms: ['Spotify', 'Apple Podcasts', 'Google Podcasts'],
        recordingFormat: 'Video & Audio',
        averageLength: '60-90 min',
    },
];

export const mockBookings = [
    {
        id: 1,
        guestId: 1,
        guestName: 'Sarah Johnson',
        hostId: 1,
        hostName: 'Alex Rivera',
        podcastName: 'The Innovation Hour',
        status: 'scheduled',
        scheduledDate: '2025-12-25T10:00:00',
        duration: 60,
        price: 500,
        topic: 'The Future of AI in Business',
        notes: 'Focus on practical applications and ethical considerations',
        createdAt: '2025-12-10T14:30:00',
    },
    {
        id: 2,
        guestId: 2,
        guestName: 'Michael Chen',
        hostId: 2,
        hostName: 'Lisa Thompson',
        podcastName: 'Mindful Living',
        status: 'pending',
        requestedDate: '2025-12-28T15:00:00',
        duration: 45,
        price: 350,
        topic: 'Building Sustainable Productivity Habits',
        notes: 'Would love to discuss the 5AM routine',
        createdAt: '2025-12-15T09:20:00',
    },
    {
        id: 3,
        guestId: 3,
        guestName: 'Dr. Emily Rodriguez',
        hostId: 1,
        hostName: 'Alex Rivera',
        podcastName: 'The Innovation Hour',
        status: 'completed',
        scheduledDate: '2025-12-10T14:00:00',
        duration: 60,
        price: 400,
        topic: 'Mental Health in Tech Industry',
        notes: 'Discuss burnout prevention strategies',
        createdAt: '2025-12-01T11:00:00',
        completedAt: '2025-12-10T15:00:00',
        rating: 5,
        review: 'Excellent conversation! Dr. Rodriguez provided incredible insights.',
    },
];

export const mockMessages = [
    {
        id: 1,
        bookingId: 1,
        senderId: 1,
        senderName: 'Sarah Johnson',
        message: 'Hi Alex! Looking forward to our conversation about AI in business.',
        timestamp: '2025-12-18T10:30:00',
        read: true,
    },
    {
        id: 2,
        bookingId: 1,
        senderId: 1,
        senderName: 'Alex Rivera',
        message: 'Me too! I\'ve prepared some great questions. Do you have any specific areas you\'d like to focus on?',
        timestamp: '2025-12-18T11:15:00',
        read: true,
    },
    {
        id: 3,
        bookingId: 1,
        senderId: 1,
        senderName: 'Sarah Johnson',
        message: 'I think practical applications and ethical considerations would resonate well with your audience.',
        timestamp: '2025-12-18T11:45:00',
        read: false,
    },
];

export const mockReviews = [
    {
        id: 1,
        bookingId: 3,
        reviewerId: 1,
        reviewerName: 'Alex Rivera',
        reviewerRole: 'host',
        rating: 5,
        comment: 'Dr. Rodriguez was an amazing guest! Professional, insightful, and engaging. Highly recommend!',
        createdAt: '2025-12-10T16:00:00',
    },
    {
        id: 2,
        bookingId: 3,
        reviewerId: 3,
        reviewerName: 'Dr. Emily Rodriguez',
        reviewerRole: 'guest',
        rating: 5,
        comment: 'Alex is a fantastic host. Well-prepared questions and great conversation flow. Would love to come back!',
        createdAt: '2025-12-10T16:30:00',
    },
];

export const bookingStatuses = {
    pending: {
        label: 'Pending',
        color: 'warning',
        description: 'Awaiting response',
    },
    accepted: {
        label: 'Accepted',
        color: 'info',
        description: 'Booking accepted, awaiting schedule',
    },
    rejected: {
        label: 'Rejected',
        color: 'error',
        description: 'Booking declined',
    },
    scheduled: {
        label: 'Scheduled',
        color: 'success',
        description: 'Recording scheduled',
    },
    in_progress: {
        label: 'In Progress',
        color: 'primary',
        description: 'Recording in progress',
    },
    completed: {
        label: 'Completed',
        color: 'success',
        description: 'Recording completed',
    },
    cancelled: {
        label: 'Cancelled',
        color: 'error',
        description: 'Booking cancelled',
    },
};
